### ISSUE TITLE
(AA) Could not find player pain animation

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#134]
Getting these warnings if player has a falling damage (developer 1):
```
WARNING: Could not find player pain animation 'stand_hit_back'

WARNING: Could not find player pain animation 'rifle_stand_hit_back'

WARNING: Could not find player pain animation 'pistol_stand_hit_back'
```

**Comment by smallmodel** [comment]
Fixed in d50128505795d6099c4c4a3050a4e18865665773

**Comment by bulldozerecske** [comment]
Updated binaries to the latest (OpenMoHAA 0.61.0-alpha+314.cf1dbf0 win_msvc64-x86_64 Feb 04 2024 UTC) and in SH still getting 

`WARNING: Could not find player pain animation 'stand_hit_back'`
