### ISSUE TITLE
(SH & BT - Gewitter) no bullet hit effect for tank traps

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#164]
There is no metal bullet hit effect when you shoot at tank traps... bullets go through the model...
![image](https://github.com/openmoh/openmohaa/assets/8028500/c8e277d0-4b50-461e-85e5-d751a2eb574b)

**Comment by smallmodel** [comment]
Fixed in commit 5cadab46abdbf9366db1741c24cccf628b52e36c

**Comment by bulldozerecske** [comment]
I re-tested them again and still not perfect. When you shoot from different angle and/or distance, there is no effect.
