### ISSUE TITLE
(Spearhead t2|4) Find the captain - the image in the game shakes quickly up and down

### ISSUE THREAD

**Issue by gbudny** [openmoh/openmohaa#286]
Hi

I want to inform you that the image in level t2|4 shakes quickly up and down. In this case, It almost always happens during a second objective. It never stops after this point.

Can you fix it?

**Comment by smallmodel** [comment]
I don't understand what image is being referenced

**Comment by gbudny** [comment]
Hi

I'm sorry that my explanation isn't clear to you. I made a video about it. 

In this case, I don't follow a captain with every step to see this bug with a cheat code: dog. When I have this glitch, every German soldier is dying without any reason. You can see this in this video. 

Can you fix it?

**Comment by smallmodel** [comment]
It should be fixed by now

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

I checked the new version of OpenMoHAA, but I still have the same issue.

**Comment by gbudny** [comment]
Hi

I attached a save game when OpenMoHAA starts to have this issue.

https://we.tl/t-SxejbIwUrz

I hope that now you can sort out this issue.

**Comment by smallmodel** [comment]
The game will kill you if you go too far before the 2nd objective (behind the church, flakk, etc.)

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

I noticed this issue in both places you mentioned it.
Something similar is happening in the original game. I don't know if soldiers inside buildings also die in this way when I trigger this "bug." 

![Tooltip_002](https://github.com/openmoh/openmohaa/assets/13519111/9b6b4e9a-2852-4e92-bea5-34923d883d56)

It happens when I try to walk closer to this soldier instead of shooting him from a longer distance. I know OpenMoHAA should resemble the gameplay of the original game. In this case, the behavior of OpenMoHAA shouldn't be changed in this level. However, I don't know why I encountered it so often.

Do you think that the commanding officer more quickly kills this German soldier in the original game than in OpenMoHAA? 

Maybe this is the reason why this issue is so noticeable in OpenMoHAA.

**Comment by smallmodel** [comment]
It's probably because that soldier get killed sooner in the original game

**Comment by smallmodel** [comment]
Closing this as it's how the map works originally
