### ISSUE TITLE
Textures Issue on map "St.Goarhausen" (obj/obj_stg)

### ISSUE THREAD

**Issue by Jardi-Gol** [openmoh/openmohaa#834]
**Describe the bug**
The map runs 100% with AA and SH. Using BT Client doesn't run properly. Tested also having him in the different folder (mainta, maintt) but the issue is still reproducible.

**To Reproduce**
1. Add the .pk3 file in any of the 3 client folders (main, mainta or maintt);
2. Run BT Client;
3. Run the map obj/obj_stg;
4. Issue with textures on the sky is reproduzed.

**Expected behavior**
Map should run smooth like with AA or SH Clients.

**Screenshots (OPTIONAL)**

<img width="1134" height="908" alt="Image" src="https://github.com/user-attachments/assets/2b2be448-2e5c-4f24-8dd2-3ada501b208e" />
<img width="1133" height="909" alt="Image" src="https://github.com/user-attachments/assets/33fd8195-717a-4d2f-af4b-c2e52ea4f87e" />

**Logs**
N.A.

**Version information (please complete the following information):**
 - OS: Windows
 - OS Version 10
 - OpenMoHAA Version: Medal of Honor Spearhead 2.16+0.83.0 (OpenMoHAA 0.83.0-dev+1019.b839d55) win_msvc64-x86_64 Nov 13 2025 UTC

**Dump (OPTIONAL)**
N.A.

**Additional context (OPTIONAL)**
Map in use for years at our server.
Download at:
[obj_stg.zip](https://github.com/user-attachments/files/23568500/obj_stg.zip)

**Comment by SFXGold** [comment]
i fixed it...will upload fix in a bit

**Comment by Jardi-Gol** [comment]
Hello @SFXGold .
Indeed the maps is working. Both Client and Server must have the same file.
In any case, I can still see some issues.

<img width="1130" height="861" alt="Image" src="https://github.com/user-attachments/assets/b7e0e6a2-cdf3-4fca-b7be-8bb99ae330c7" />
<img width="1132" height="910" alt="Image" src="https://github.com/user-attachments/assets/f7e6a311-b95c-4f96-9740-2ea5704bb33e" />
<img width="1133" height="908" alt="Image" src="https://github.com/user-attachments/assets/9fc5a10f-ceda-43f9-93c8-75c9af988e4f" />

Since I'm not aware if it might be my client (original version of MOHAA+SH+BT) I am sharing my Client Version just to see if anyone see the same as me.

https://drive.google.com/file/d/19vudoqzZjRtJwe9mqY05qXLrqNGZP_50/view?usp=sharing

We play for years with SH so that's the reason this issue is coming now when tried to play with Breakthrough instead.
Thank You very much for anyone that can test with my client.
Let me know your feedback.

**Comment by Jardi-Gol** [comment]
OK. I can close this ticket.
@SFXGold fixed the missing textures that Breakthrough could not read and the map is working fine with both clients.
Thank You very much all for the help and effort solving this issue.

Best Regards
